import React from "react";
import '../css/Journey.css'

export default function Journey() {
    return (
        <div className="journey-container">
            <h1>My Journey</h1>
            <h2>Daydreams</h2>
            <p>Ever since I was a child, I've always had my face buried in some type of technology. Computers, TVs, game consoles, and everything in between. Every minute spent with technology was like I was being drip fed high concentrated amounts of dopamine. My family always told me that I had a future in tech, and while it seemed exciting, I never really took it seriously. I would just consume all that technology had to offer, because that's just what was put in front of me on a constant basis. I would incessantly daydream about creating that next big video game, website, or animation with the latest tools, but as a child, you kind of go through phases, always discovering. In my case, I also struggled with focusing just in general, along with the fact that I didn't even have my own computer to do the things I always dreamt of doing, so I just continued on living what are supposed to be "the best times of your life."</p>
            <h2>Blur</h2>
            <p>Even with the thousands of hours of experience addicted to technology, I still never truly applied myself in creating something, though I dabbled in it here and there. Graduating high school was a bittersweet experience, in that I was free to do whatever I wanted, yet I was too comfortable being... comfortable. I never had this sense of urgency to do anything outside of my comfort zone, even though my mind was constantly itching to break outside of my usual norm. My young adult years went by in such a dull way, sometimes I wonder if they even existed. A bit of college, tense relationships, scattered friendships... Life was going by in a non-exciting blur.</p>
            <h2>Push</h2>
            <p>After years of a seemingly never-ending onslaught of issues, including the infamous COVID outbreak, I decided that I needed to do something different. I had to teach myself to go beyond what I was used to, even if sometimes I felt alone through it all. Eventually I happened upon a company that was offering to teach people the basics of HTML all the way up to learning about React. There were even some talks about web development apprenticeships being handed out, as long as you showed passion. I'll be honest, I almost didn't go, even after I paid what little I had just to partake in the classes. I pushed through my pessimistic thoughts and attended anyways, and I think without that action, I wouldn't even be making this portfolio. I was still uncertain about the future, but being in those classes showed me that I was capable of not just actively pursuing my own goals, but that I also had the ability to lift up others that were also in my place of spiraling anxiety.</p>
            <h2>Change</h2>
            <p>After some time spent learning about HTML, CSS, Bootstrap, Mobile Responsiveness, JavaScript, and talking with people at this company, I remember sitting at my desk after a rough day, and checking my email, just hoping that things would change. That's when I saw the apprenticeship offer. I just remember sitting back and letting the tears flow, because this was one of the first times in my life that I actually felt like I was finally heading into a direction that wasn't just filled with the same hum and drum. I immediately filled out the forms accepting the apprenticeship, and quit my school job at the time. I was finally going to show everyone, and most importantly myself, that I had the drive to make change.</p>
            <h2>The Apprenticeship</h2>
            <p>The apprenticeship was an interesting time. I was in constant communication with other developers and apprentice specialists, diving deep into other frameworks and technologies, gaining valuable work and project experience, and acquiring more connections, some I still hold onto today, than I knew what to do with. I went from building a simple to do list to having to adjust to true real-world applications and websites, with a structured work flow, lines of code that could go around the world multiple times, and experienced developers helping me understand every single piece in the puzzle.</p>
            <br></br>
            <p>I spent about a year and four months at this apprenticeship, and knew that the end was drawing near. There was a lot of anxiety with the other apprentices about whether they were going to be offered a job or not, but I knew that I not only worked good with my team, but that I also volunteered my free time helping other apprentices, pre-apprentices, and even made some speeches for the company. The timer was slowly counting down to zero, and I waited patiently for someone to let me know about a job, especially after getting interviewed for a position in the company. The last day of the apprenticeship came about, and then...</p>
            <h2>Tribulation</h2>
            <p>After getting my last paycheck from the apprenticeship, I was left with this sense that I may have done something wrong. What was wrong with me? Was I not good enough? Should I have done more? What am I supposed to do now? It's like I was calling out to the heavens, and receiving no answer while I'm drowning. There were many different feelings stirring around in my heart and mind, and I decided to really try and figure out where I was in life, and what I was supposed to do next. I'm used to disappointment, so maybe I wasn't affected by the end of the apprenticeship as much as other people. Life happens sometimes. I talked with many people about the situation, and I was greeted with comfort and reassurance. It's true what they say... A strong community can really help dampen the bad that happens in your life.</p>
            <h2>Anticipation</h2>
            <p>Sometime after the apprenticeship ended, I just went about my life as usual, just with a huge amount of freedom. Aka, being unemployed. Day by day, I tried my best to keep from going back to how it used to be. Existing for the sake of existing as the world goes 'round and 'round. It's just that I struggled with the fear of putting myself out there. I was simply comfortable with being comfortable. Then... Something clicked. I'm not exactly sure what caused it, but little by little, I started to get back into pursuing my goals. I was focusing longer, working harder, anticipating the challenges that would inevitably come, and became obsessed with fine tuning not only my projects, but fine tuning myself as a person, and finally accepting that I was going to hurt, whether I took charge or not, so may as well take charge with the hope that things will work out in life. That's how I finally got to this point of creating this portfolio website and writing out a bit of my journey.</p>
            <h2>Future</h2>
            <p>I'm currently hammering away at more projects and absorbing as much knowledge as I can to really stand out in this software developer path that I've decided to take. I'm now in a state where I'm more confident in myself, my abilities, my feelings, my thoughts, and slowly letting myself be in a position where I'm not only rising myself up, but others too. I'm not too sure where things will go from here, but I do know that I'm going to continue putting in the efforts that I now know that I'm capable of. Hopefully in the future, I can give back to the people that have helped me get to where I am today.</p>

        </div>
    )
}